on: push
jobs:
  test_lint_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/Checkout@v3
        # nodejs exists on ubuntu-latest. installing to practise
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
      - name: Deploy
        run: |
          npm build
          echo "deploying"
